BoxLayout:
    orientation:'horizontal'

    BoxLayout:
        orientation:'vertical'

        Button:
            text: 'Calculate score'
            on_press: app.handle_calculate()
        Button:
            text: 'Clear'
            on_press: app.handle_clear()


    BoxLayout:
        orientation: 'vertical'

        TextInput:
            text: ''
            id: score_input

        Label:
            text: 'Enter score above to calculate grade'
            id: score_output

